travis:
  secure:
    BINSTAR_TOKEN: c2z/4o+SFGM4vafhKX92qoV3ERjfI60GDJ+/NU8psaWwgngl2WeFXA1c1udS1YbLGCIPb0PZY28AGi+5vr5NutXpxDfjyls+jvucETzKFUV3tQbLgQcLrEOSi8uU3zDV/BXF/85S+P8PsH9HpNPrqAIe+C/N1g2jrOGRy9qwQvqvoO4sXBBbI/uJFqNwJDcv/B13g0UDL0VbwcKksCxp8vcpOZ7rkRlf47RI7bCunjSSqyUZltbvwLam3JmFuyvt6Gp9PD9L23HL202KgREuVt3Nfdv8Ub3X1Z6eB5/a9/ALQJ45glvQkag8lhDlFx03/cJcLLF4Pmw6YwABu87zfdz6cEV6I65RAaVcOolrUprX7P2c4T91lWYRjC3/DwcqNIO2jSQRZJYUT5HnGgtgZeRc2+XhACk/ruEgoiTpES5awpfE4GeBAPsy/GMyDm0TpCYPHefux3Z8bawjrh5pF/up2yqY+KILbE9y3DFwWh9wuQmQcIrGzJ9W6toIqJ/+2yWGnHVdyBd4923w8NeYfnyXkOxBwcaIISfiPX/qCiOsIl8dBjp8Pe7DZhp0kx5lfb4qdkAH5ZSntXKPZwqKpChBWyBcEOpjEwpBKx0ViKXbN3XcaiXreSMOPkzrDfoM1ri/GkpiJ7iBBdNjeL2lTNYkQ8mMO9aeR4ZpuO/4gsc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
