travis:
  secure:
    BINSTAR_TOKEN: coLIUFhsxipzH1wnwNVtf2OT3N80H/3BO73LRlEvS2JOTO+8JRiZ6Ruc+crVDzjO+F9PpVAVzBcmA/YaydTQTjS1K6y/1wUFUKVosWIE+aQDAm08lVqgtstF1R5NtTy61q0v4dpoywflq0No5qh1W2G2KNj+nAieUD5DIIqA2WUZCD9o3AWAMl2iI1P3IReB4ZwljnJWwlLdSx/YJ4ZC95U0W49Ga93ku5E5u4GDpjVKl8JDuONMx29O8sbIpTHbkIGt/N/MW25U7De2GA4a2waX4s4KqQQhxgQ/t+sZp8j17/6B6ltIG7Z4su7OKOr3C2uTBm5JpoNb5GD4ChTPZkWN+jquufYcyjFK57Gy45MFBCOLlWoUUtDzwRq5dmVkq6fMftpy3h1xbDaZ3yc3Uihwhff8V72zimPnvd0/wjPsduODeaQ3WxiL1UX3R+oDhMTgfqTv2AdRj8Em4bV0DZwpvr/qOwpDRfWzDrYzK8LjVyPV6diy40nPXQqGYLznx8s2KH+Tk+Uba6V2+/TfMi4Ck2P0xZdsTsyadok7G8/Dfy0Ix45SqgYj+9MKjSIsJerhnsBIMezxJ3Ln0NgeT0hmjc9jn5oKrwQjdo5Sjlr1Jy51WcX+yTmuMJclnV8Pxkl21Sy6U3QhVH6OHx3uyS9pEe/f8B6bWNghUMwEJN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
